### ISSUE TITLE
iGPU only variant

### ISSUE THREAD

**Issue by ludalex** [leto1210/z390-Hack#10]
Hello there, 

I have roughly your same setup, minus the AMD dGPU. I've tried to use your EFI folder with no success, with the only difference in the bios settings with: 

Primary Display: ~PCIE~ -> CPU
iGPU Multi Monitor: ~Enabled~ -> Disabled

Unfortunately it doesn't boot. Are there any changes I need to apply to your configuration if I just want to use my HD 630 IGPU?

**Comment by leto1210** [comment]
Hello,

Sorry for delay :-)

Yes you have to change your bios settings but you have to modify the config.plist.

In the section PciRoot(0x0)/Pci(0x2,0x0) you have to set AAPL,ig-platform-id with another value.

> Change 0300913E by 07009B3E

Note: With macOS 10.15.5, there seems to be a lot of issues with black screen using 07009B3E, if you get similar issues try swapping to 00009B3E

Regards

**Comment by leto1210** [comment]
Hello,

Full example for a desktop UHD 630 without a dGPU:

Key | Type | Value
-- | -- | --
AAPL,ig-platform-id | Data | 07009B3E
framebuffer-patch-enable | Data | 01000000
framebuffer-stolenmem | Data | 00003001

**Comment by ludalex** [comment]
Thanks a lot. I managed to get it working!
