### ISSUE TITLE
Big Sur compatibility

### ISSUE THREAD

**Issue by ludalex** [leto1210/z390-Hack#11]
Any chance you managed to get this motherboard to work with Big Sur 100%?
I almost did, the only issue I have is that it fails to wake from sleep. I'm using iGPU only.

**Comment by leto1210** [comment]
Hello,

I made several test and I'm not totally satisfied for the stability. I plan jumping to Big Sur with the next update.

**Comment by leto1210** [comment]
Hello,

If you still have the problem, please have a look to my last pre-release for OC 063. That will fix your issue.

Regards

**Comment by ludalex** [comment]
Awesome. What was the issue?

**Comment by leto1210** [comment]
To be honest, I'm not able to reproduce exactly your issue has I'm in a DGPU configuration.

For OC63 update, I've checked all my parameters of my config.plist, remove unwanted kexts and backward some Quirks settings.

So have a try ;-)

**Comment by leto1210** [comment]
Big Sur compatibility is ok with release v066
