### ISSUE TITLE
Black stripes when turning on

### ISSUE THREAD

**Issue by xavik0f2** [leto1210/z390-Hack#12]
Hi,

I have the same configuration and I have a wrong behaviour, every time I turn on the PC, black stripes appear in the login window, not during boot. If I turn the monitor on and off then everything is fine. Have you ever had this problem? (Dual screen)

**Comment by leto1210** [comment]
Hello,

I heard about some common problem with dual screen, some times you have to look on how you have connected your screens. You should to try with other ports combination (between HDMI and DP ports).

Thk
