### ISSUE TITLE
OC 0.6.6

### ISSUE THREAD

**Issue by ludalex** [leto1210/z390-Hack#13]
Any chances you will package a release for OC 0.6.6 update? Would like to upgrade my system since it's based on yours but I'm afraid to mess it up due to the new bootloader system.
Thanks!

**Comment by leto1210** [comment]
Hello,

Version 066 is under validation ;-)

**Comment by leto1210** [comment]
Hello,

Please have a look to the pre release [v066](https://github.com/leto1210/z390-Hack/tree/v066)

**Comment by ludalex** [comment]
Works great with my system, thanks!

Only struggle I have is with having `OpenShell.efi` enabled in the auxiliary programs in the boot picker:
I set [this](https://github.com/leto1210/z390-Hack/blob/32ea3eb0c80a27efea1d150d065c885c14d309e3/EFI/OC/config.plist#L435) to false and [this line](https://github.com/leto1210/z390-Hack/blob/32ea3eb0c80a27efea1d150d065c885c14d309e3/EFI/OC/config.plist#L632) to true in order to have it shown in the boopicker but I get "OC: Failed to parse configuration". If I revert the changes it boots correctly so I know 100% my `config.plist` is not malformed in any way (also ran it through the sanity checker). Maybe I'm going wrong with enabling OpenShell?

**Comment by leto1210** [comment]
Hello,

I'm unable to reproduce your problem. After setting OpenShell.efi to true in tools section, I do a nvram reset and Openshell selection is ok on boot.
