### ISSUE TITLE
Which DMG file should i use?

### ISSUE THREAD

**Issue by KidJynx** [leto1210/z390-Hack#14]
is it okay if i use this one? https://community.hackintoshshop.com/files/file/49/download-hackintosh-catalina/

**Comment by leto1210** [comment]
Hello,

You have to download dmg with Mac App Store or use only link from Apple Support website.
Big Sur --> https://support.apple.com/en-us/HT201475

Thomas

**Comment by KidJynx** [comment]
i am using a windows. any way to do it on windows?

i downloaded the BigSur DMG and used TransMac to write it on the USB but i am not able to access the EFI folder on it.
