### ISSUE TITLE
how to fix black screen issue (NO HDMI out)

### ISSUE THREAD

**Issue by KidJynx** [leto1210/z390-Hack#15]
is it possible to make the USB on windows? if yes can you tell how. 

thank you.

**Comment by KidJynx** [comment]
how to fix the black screen HDMI port no display issue while installing?

**Comment by leto1210** [comment]
Hello,

There is a lot of reason possible.

Please have a look on https://www.tonymacx86.com/ Forum.

By the way, by default, I recommend to always use displayport.

Regards
