### ISSUE TITLE
USBPorts.kext or SSDT-UIAC.aml and SSDT-USBX.aml

### ISSUE THREAD

**Issue by efortin** [leto1210/z390-Hack#2]
The configuration is duplicated: you need to choose USBPort.kext or ACPI patch method( SSDT-UIAC.aml and SSDT-USBX with USBInjectAll.kext), thanks to hackintool documentation.

> Use the “Export” button to generate files to your Desktop
Copy SSDT-EC.aml (if created) to EFI/CLOVER/ACPI/patched
Choose one of the following two:
Copy USBPorts.kext to EFI/CLOVER/kexts/Other or;
Copy SSDT-UIAC.aml and SSDT-USBX.aml (if created) to EFI/CLOVER/ACPI/patched

**Comment by leto1210** [comment]
Done in merge request #3
